Repository openshift/managed-prometheus-exporter-ebs-iops-reporter, pull requests merged in 2019-05, with the labels that each got.

#9 Updated OWNERS to be consistent with SRE operators
  OWNERS
Labels: lgtm, size/XS

#8 Added selectorsyncset generation
  .gitignore
  Makefile
  project.mk
  scripts/generate_syncset.py
  scripts/templates/selectorsyncset.yaml
Labels: approved, lgtm, size/M

#10 Added all requirements for app-sre pipeline
  .gitignore
  Makefile
  hack/00-osd-managed-prometheus-exporter-ebs-iops-reporter.selectorsyncset.yaml.tmpl
  hack/app_sre_build_deploy.sh
  hack/app_sre_pr_check.sh
  project.mk
  scripts/generate_syncset.py
  scripts/templates/selectorsyncset.yaml
Labels: size/L

#11 Fix name of selector sync set
  hack/00-osd-managed-prometheus-exporter-ebs-iops-reporter.selectorsyncset.yaml.tmpl
  scripts/templates/selectorsyncset.yaml
Labels: size/XS
