Repository openshift/managed-prometheus-exporter-ebs-iops-reporter, pull requests merged in 2019-03, with the labels that each got.

#1 SREP-923: Relocate EBS IOPS reporting exporter
  .gitignore
  Makefile
  README.md
  deploy/.gitkeep
  functions.mk
  monitor/main.py
  monitor/start.sh
  resources/010_serviceaccount-rolebinding.yaml.tmpl
  resources/020-awscredentials-request.yaml.tmpl
  resources/040_deployment.yaml.tmpl
  resources/050_service.yaml.tmpl
  resources/060_servicemonitor.yaml.tmpl
Labels: size/XL

#2 Makefile typo fix, remove "dev" target
  Makefile
Labels: bug

#3 Remove extra/incorrect resource entry
  Makefile
Labels: bug

#4 Update init container image to redhat quay.io org
  Makefile
Labels: kind/cleanup, size/XS

#5 Update cloudcredential.openshift.io to v1
  resources/020-awscredentials-request.yaml.tmpl
Labels: lgtm, size/XS

#6 Missed AWSProviderSpec version
  resources/020-awscredentials-request.yaml.tmpl
Labels: size/XS

#7 Updated initcontainer to new quay.io/openshift-sre org
  Makefile
Labels: size/XS
